# comes from https://github.com/btkruppa/angular-spring-boo-dev-ops/blob/master/buildspec.yml
version: 0.2

phases:
  post_build:
    commands:
      - cd angular-boot && mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'angular-boot/target'
